### ISSUE TITLE
Main Chatroom

### ISSUE THREAD

**Issue by remotevase** [MineCode-Devs/DevMine#5]
Okay... The title says it all

**Comment by remotevase** [comment]
So @AmiroEmad when will you finish Server Manager? Hopefully in the next week... Also, remember what I said in B2 chat: Upload beta builds to their corresponding branches. Then, Create new branch called B2 off of B1. In the B2 branch will have the code from B1. Then we can work on B2 in the B2 branch.

**Comment by MiroTheSuperDev** [comment]
my network speed is so bad and when i upload it is so slow uploading

**Comment by MiroTheSuperDev** [comment]
also github desktop have some problems with this respiratory so you should delete and re create it and extract b1 zips and upload files in it

**Comment by MiroTheSuperDev** [comment]
wait i have an idea why not create a new branch and let me test github desktop on it

**Comment by remotevase** [comment]
sure

**Comment by TheProest35YT** [comment]
Can I make a fork of DevMine when it Is Stable ?

**Comment by MiroTheSuperDev** [comment]
so what changes did you do to beta one remote vase is it only file copying as i requested or something else is changed i just need to know the following data to know exactly what i will do

**Comment by remotevase** [comment]
It is only:
1. file copying
2. Renaming the file paths in the files (changing the use statements from 
use pocketmine/... (Old folder structure)
tO
use DevMine/...(new folder structure)

**Comment by MiroTheSuperDev** [comment]
but did you change any inner code ??

**Comment by MiroTheSuperDev** [comment]
and was this done manually or by find and replace because i think the problem came from find and replace

**Comment by remotevase** [comment]
@AmiroEmad This is what I see:

``` php
[*] devmine set-up wizard
[*] Please select a language:
 English => eng
 τ«ÇΣ╜ôΣ╕¡µûç => chs
 τ╣üΘ½öΣ╕¡µûç => zho
 µùÑµ£¼Φ¬₧ => jpn
 ╨á╤â╤ü╤ü╨║╨╕╨╣ => rus
[?] Language (eng): eng

Fatal error: Uncaught UnexpectedValueException: DirectoryIterator::__construct(C:\Users\Praji\Desktop\DEVMINE\src/devmine/languages/installer/,C:\Users\Praji\Desktop\DEVMINE\src/devmine/languages/installer/): The system cannot find the path specified. (code: 3) in C:\Users\Praji\Desktop\DEVMINE\src\devmine\utilities\installer\InstallerLang.php:26
Stack trace:
#0 C:\Users\Praji\Desktop\DEVMINE\src\devmine\utilities\installer\InstallerLang.php(26): DirectoryIterator->__construct('C:\\Users\\Praji\\...')
#1 C:\Users\Praji\Desktop\DEVMINE\src\devmine\utilities\installer\Installer.php(40): devmine\utilities\installer\InstallerLang->__construct('eng')
#2 C:\Users\Praji\Desktop\DEVMINE\src\devmine\server\DevMine.php(435): devmine\utilities\installer\Installer->__construct()
#3 {main}
  thrown in C:\Users\Praji\Desktop\DEVMINE\src\devmine\utilities\installer\InstallerLang.php on line 26
```

**Comment by Super35** [comment]
Isn't this the same as #4 or its just different

**Comment by Super35** [comment]
Wait where's Taki
Will there be  like a DevMine.phar
Just asking

**Comment by remotevase** [comment]
DevMine.phar: coming soon
Taki is busy with school, so am I, but I have less homework than him,so I have more time to get on GitHub

**Comment by Taki21** [comment]
hey! howd u know :p

**Comment by Taki21** [comment]
Well true i do get more

**Comment by remotevase** [comment]
take a guess... I can easily drive over to your house... No problemo!

**Comment by Taki21** [comment]
xD

**Comment by Taki21** [comment]
At least i have french this year NOT SPANISH THANK GOD :P

**Comment by Super35** [comment]
You guys are the same country ?!

**Comment by Super35** [comment]
Taki when you comment in my country it's in 9:57a.m

**Comment by Ad5001** [comment]
@Taki21 I don't think French is easier than Spanish... But I don't speak spanish so I can't judge x)

**Comment by Super35** [comment]
... I think after a few days / months the chatroom will be Spammed mostly

**Comment by remotevase** [comment]
@Ad5001 @taki21
In my school, you get to choose either Spanish, French, or Italian at the end of 6th grade. From last year (7th grade) through all of high school (12th grade) you take the language that you chose. I chose French, and as far as I can tell, French students have learned a lot more than the Spanish and Italian students over just the course of 7th grade. French is clearly the easiest out of the three m

**Comment by remotevase** [comment]
@TheProest35YT-- not only are me and taki in the same country, we are also same state! 
Also, btw, it was 9:57 PM here in our state when he posted that

**Comment by Taki21** [comment]
lol :p @Ad5001 i was born in canada.

**Comment by Super35** [comment]
So you guys are Canadians or Americans

**Comment by Super35** [comment]
Btw , when are we talking about DevMine ?

**Comment by Ad5001** [comment]
@remotevase Maybe, I did not study Spanish ( choosed German )
@Taki21 Oh ok :)
@Super35 I don't think anymore ...x)

**Comment by Taki21** [comment]
Im dead... According to my calculations i cant use github or have time to code!!!! TOO MUCH WORK :P

**Comment by Taki21** [comment]
Im Canadian ONLY

**Comment by MiroTheSuperDev** [comment]
I have two weeks before school starting that i can code in devmine error seems not very big

**Comment by remotevase** [comment]
@Super35 just because we live in America doesn't mean that we are Americans... I'm not American at all!

**Comment by remotevase** [comment]
@AmiroEmad okay then. If you could possibly get a non-buggy B2 uploaded, then I will update the code, and then we are good to go!

**Comment by TheProest35YT** [comment]
So you guys are which Nationality ?

**Comment by Super35** [comment]
So then we make plugins for DM ?

**Comment by remotevase** [comment]
yes. plugins will be the last thing that we do...

**Comment by MiroTheSuperDev** [comment]
I finished fixing it took me 3 minutes lol

**Comment by MiroTheSuperDev** [comment]
now all i get after fixing is blank

**Comment by MiroTheSuperDev** [comment]
![image](https://cloud.githubusercontent.com/assets/15315415/18419551/81a8c7be-7812-11e6-8012-5986fd5a9157.png)

**Comment by MiroTheSuperDev** [comment]
The problem is with the installer

**Comment by remotevase** [comment]
???

**Comment by remotevase** [comment]
Sorry... Sometimes I am honestly a PHP noob while other times, I am decent at PHP

**Comment by Super35** [comment]
Remote can you be admin of my server?

Server IP: CraftedPE.playmc.pe
Port: 53991

**Comment by Super35** [comment]
And btw I don't know what's grade grade grades in America because my country have 4different ranks for 4 different schools :p

**Comment by Taki21** [comment]
wow so simple :p so in ur terms we basically have 14 "ranks" Grade School is for 14-15 years (more or less)

**Comment by remotevase** [comment]
@Taki21  that would be awesome

**Comment by remotevase** [comment]
Preschool, Kindergarten, 1st grade, 2nd grade, 3rd grade, 4th grade, 5th grade, 6th grade, 7th grade, 8th grade, 9th grade, 10th grade, 11th grade, 12th grade, 4 years of college, finished...
We basically have school until we are 18 years old, then we have college until we are 22 years old. After that, we work until we are in our 70's or 80's. Then we retire and live off of our life savings

**Comment by Super35** [comment]
For me it's Kindergarten or Preschool (Your Choice) then Primary School which is 6 - 13years old then Secondary School which is 4 -5 years depending on your choice too then Polytechnic or Junior College then University then End Of School which is 18-20 years old in my country

**Comment by Super35** [comment]
Remote can you be admin of my server?

Server IP: CraftedPE.playmc.pe
Port: 53991

**Comment by remotevase** [comment]
@TheProest35YT I only play on 0.16 now. I can't join your server

**Comment by Super35** [comment]
How you update so fast !?

**Comment by remotevase** [comment]
There is something magical called beta testing

**Comment by Super35** [comment]
... I didn't know 0.16 can be tested

**Comment by remotevase** [comment]
honestly, your senselessness amuses me

**Comment by Taki21** [comment]
lol i think hes playing with us

**Comment by remotevase** [comment]
no, @Taki21 i think he is just dumb when it comes to this stuff...

**Comment by Taki21** [comment]
**HONESTLY** i find it rude to call someone dumb even if u think that inside i wouldnt like to say it in public. It also makes us look like we're a know it all in a way... MY OPINION. This is not fact :p

**Comment by remotevase** [comment]
srry, lel

**Comment by Taki21** [comment]
its ok i didnt mean this in a mean way though xD

**Comment by Super35** [comment]
And btw I know how to beta test just go Google Play's Site to do it

**Comment by remotevase** [comment]
@AmiroEmad  any updates on fixing issue? Idk how to do it...

**Comment by MiroTheSuperDev** [comment]
The problem is with file locating my first attempt to fix after it i got a
black screen when running pocket mine which means console php script is
having a bug i am now in school and grade 9 so i have much hard work to do
and home works but i promise that i will finish it one day maybe on a
weekend or something like that if i have successful fixing i will push my
changed to github

**Comment by remotevase** [comment]
Okay thanks!

**Comment by Super35** [comment]
@remotevase @Taki21 @Ad5001 @AmiroEmad 
Do you guys want to join @DMPlugins ?

P.S: Delete the org if you want

**Comment by MiroTheSuperDev** [comment]
I don't have time to contributed to the projects I started and the teams I
am in.     I don't think that it will be good thinking if I joined another
team

**Comment by Super35** [comment]
OK then I'll delete

**Comment by Super35** [comment]
Are you guys busy with school or Coding for DevMine

**Comment by remotevase** [comment]
School

**Comment by MiroTheSuperDev** [comment]
School 😢

**Comment by Super35** [comment]
Is Java Or Php coding easier

**Comment by remotevase** [comment]
PHP

**Comment by MiroTheSuperDev** [comment]
So i was reading the readme and found that we are working on a project that have lots of bugs that need to be fixed ImagicalMine

@remotevase we really need to change this to pmmp to Genysis asap

**Comment by remotevase** [comment]
Yes once the main php.exe startup (blankscreen) bug is fixed, we will update the files again to genisys

**Comment by Super35** [comment]
what will happen to DevMine?(last commit= Jan 12 , 2017)

**Comment by MiroTheSuperDev** [comment]
MineCraft is no longer popular 

So what will happen is people moved on to other games

And I moved to Roblox

**Comment by MiroTheSuperDev** [comment]
But I will never give up on my friends
I have improved my PHP a little more bit
So @remotevase if you need any kind of help in fixing a bug or in testing or in code just tell me

**Comment by remotevase** [comment]
Minecraft is still popular, but not for me. @TheRoyalBlock does not wanna do server softwares so IDK

**Comment by AvgZing** [comment]
No way am I getting involved with this. Cya!

**Comment by Super35** [comment]
RIP Project I guess

**Comment by Taki21** [comment]
minecraft pc not ded m8

**Comment by MiroTheSuperDev** [comment]
I was talking about Minecraft pe the pocketmine servers on it

But any else kind of Minecraft is still popular 

And I have played minecraft pc it is still popular

**Comment by MiroTheSuperDev** [comment]
I am no longer developing anything on MineCraft PE guys nor PC

if you need me in anything just ask me and I will be helping instantly even if you need me in minecraft

I am learning java currently and I am nearly done

**Comment by Taki21** [comment]
@AmiroEmad i am learning java too and im also nearly done lel
